# Generated by Django 4.1.7 on 2023-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_plan_alter_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.IntegerField(default=1),
        ),
    ]
