# Generated by Django 4.1.7 on 2023-03-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_plan_user_subscription"),
        ("users", "0004_alter_user_email"),
    ]

    operations = []
