# Generated by Django 4.1.7 on 2023-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_20230315_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.IntegerField(default=1),
        ),
    ]
