# Generated by Django 4.1.7 on 2023-03-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='weight',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('GRAM', 'гр'), ('MILLILITER', 'мл'), ('THING', 'шт')], max_length=20, verbose_name='Мера измерения'),
        ),
    ]
