# Generated by Django 4.1.7 on 2023-03-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0002_rename_weight_ingredient_quantity_ingredient_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGITARIAN', 'Вегитарианское'), ('KETO', 'Кето')], db_index=True, max_length=20, verbose_name='Тип меню')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='plan',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('GRAM', 'гр'), ('MILLILITER', 'мл'), ('THING', 'шт'), ('TEASPOON', 'ч.л.'), ('TABLESPOON', 'ст.л.')], max_length=20, verbose_name='Мера измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(max_length=30, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=8, verbose_name='Калорийность (на 100 грамм)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='meal_app.menu', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='meal_app.menu'),
        ),
    ]
