# Generated by Django 4.1.7 on 2023-03-15 13:20

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_menu_remove_recipe_plan_alter_ingredient_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NO_ALLERGY', 'Нет аллергии'), ('FISH_AND_SEAFOOD', 'Рыба и морепродукты'), ('MEAT', 'Мясо'), ('GRAINS', 'Зерновые'), ('BEE_PRODUCTS', 'Продукты пчеловодства'), ('NUTS_AND_BEANS', 'Орехи и бобовые'), ('MILK_PRODUCTS', 'Молочные продукты')], db_index=True, default='NO_ALLERGY', max_length=200, verbose_name='Алергия'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.IntegerField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('dessert', 'десерт')], db_index=True, verbose_name='Тип блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='meal_app.menu', verbose_name='Меню'),
        ),
    ]
