# Generated by Django 4.1.7 on 2023-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0004_alter_plan_allergy_alter_recipe_dish_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('dessert', 'десерт')], db_index=True, max_length=20, verbose_name='Тип блюда'),
        ),
    ]
