# Generated by Django 4.1.7 on 2023-03-16 11:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0005_alter_recipe_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='plan',
            name='dish_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('DESSERT', 'Десерт')], db_index=True, default=['BREAKFAST', 'LUNCH', 'DINNER', 'DESSERT'], max_length=200, verbose_name='Типы блюд'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FISH_AND_SEAFOOD', 'Рыба и морепродукты'), ('MEAT', 'Мясо'), ('GRAINS', 'Зерновые'), ('BEE_PRODUCTS', 'Продукты пчеловодства'), ('NUTS_AND_BEANS', 'Орехи и бобовые'), ('MILK_PRODUCTS', 'Молочные продукты')], db_index=True, max_length=200, null=True, verbose_name='Типы ингредиентов'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FISH_AND_SEAFOOD', 'Рыба и морепродукты'), ('MEAT', 'Мясо'), ('GRAINS', 'Зерновые'), ('BEE_PRODUCTS', 'Продукты пчеловодства'), ('NUTS_AND_BEANS', 'Орехи и бобовые'), ('MILK_PRODUCTS', 'Молочные продукты')], db_index=True, max_length=200, null=True, verbose_name='Аллергия'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('DESSERT', 'Десерт')], db_index=True, max_length=20, verbose_name='Тип блюда'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
