# Generated by Django 4.1.7 on 2023-03-16 11:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0006_remove_plan_breakfast_remove_plan_dessert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FISH_AND_SEAFOOD', 'Рыба и морепродукты'), ('MEAT', 'Мясо'), ('GRAINS', 'Зерновые'), ('BEE_PRODUCTS', 'Продукты пчеловодства'), ('NUTS_AND_BEANS', 'Орехи и бобовые'), ('MILK_PRODUCTS', 'Молочные продукты')], db_index=True, max_length=200, null=True, verbose_name='Типы ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
    ]
